<a href="https://colab.research.google.com/github/RODIV45/Data-Analysis-with-Python-GFG/blob/main/null_value_handle_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [40]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:
path="/content/drive/MyDrive/airports.csv"
df=pd.read_csv(path)

In [42]:
df

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,NaN,US,US-AR,Newport,no,NaN,NaN,NaN,NaN,NaN,00AR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74458,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad
74459,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,NaN,NaN,NaN,NaN,NaN,NaN
74460,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,NaN,US,US-TX,Blum,no,87TX,NaN,87TX,NaN,NaN,NaN
74461,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,NaN,CA,CA-YT,(Old) Scandium City,no,NaN,NaN,NaN,NaN,NaN,"ZZZW, ZZZW, ZYW, YK96"
74462,313629,ZZZZ,small_airport,Satsuma I≈çjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,NaN,RJX7,NaN,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

In [43]:
df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,NaN,US,US-AR,Newport,no,NaN,NaN,NaN,NaN,NaN,00AR

In [44]:
df.isnull().sum()
#shows how many null rows under each column

id                       0
ident                    0
type                     0
name                     0
latitude_deg             0
longitude_deg            0
elevation_ft         14207
continent            36027
iso_country            259
iso_region               0
municipality          4986
scheduled_service        0
gps_code             33551
iata_code            65602
local_code           42339
home_link            70913
wikipedia_link       63700
keywords             57997
dtype: int64

In [45]:
df.iloc[:,6:7].values

array([[  11.],
       [3435.],
       [ 450.],
       ...,
       [ 690.],
       [   4.],
       [ 338.]])

In [46]:
impute=SimpleImputer(missing_values=np.nan,strategy='mean')
impute.fit(df.iloc[:,6:7].values)

SimpleImputer()

In [47]:
df.iloc[:,6:7]=impute.transform(df.iloc[:,6:7].values)

In [48]:
df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,NaN,US,US-AR,Newport,no,NaN,NaN,NaN,NaN,NaN,00AR

In [49]:
df.isnull().sum()

id                       0
ident                    0
type                     0
name                     0
latitude_deg             0
longitude_deg            0
elevation_ft             0
continent            36027
iso_country            259
iso_region               0
municipality          4986
scheduled_service        0
gps_code             33551
iata_code            65602
local_code           42339
home_link            70913
wikipedia_link       63700
keywords             57997
dtype: int64

In [50]:
#see clearly above that elevation has np null values

In [51]:
impute=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
impute.fit(df.iloc[:,:].values)

SimpleImputer(strategy='most_frequent')

In [52]:
df.iloc[:,:]=impute.transform(df.iloc[:,:].values)

In [53]:
df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,AS,US,US-PA,Bensalem,no,00A,AAA,00A,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,AS,US,US-KS,Leoti,no,00AA,AAA,00AA,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,AS,US,US-AK,Anchor Point,no,00AK,AAA,00AK,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,AS,US,US-AL,Harvest,no,00AL,AAA,00AL,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,AS,US,US-AR,Newport,no,00A,AAA,AMA,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,00AR

In [54]:
df.isnull().sum()

id                   0
ident                0
type                 0
name                 0
latitude_deg         0
longitude_deg        0
elevation_ft         0
continent            0
iso_country          0
iso_region           0
municipality         0
scheduled_service    0
gps_code             0
iata_code            0
local_code           0
home_link            0
wikipedia_link       0
keywords             0
dtype: int64

In [55]:
df

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,AS,US,US-PA,Bensalem,no,00A,AAA,00A,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,AS,US,US-KS,Leoti,no,00AA,AAA,00AA,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,AS,US,US-AK,Anchor Point,no,00AK,AAA,00AK,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,AS,US,US-AL,Harvest,no,00AL,AAA,00AL,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,AS,US,US-AR,Newport,no,00A,AAA,AMA,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,00AR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74458,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,00A,AAA,AMA,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad
74459,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,00A,AAA,AMA,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
74460,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,AS,US,US-TX,Blum,no,87TX,AAA,87TX,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,Mukho
74461,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,AS,CA,CA-YT,(Old) Scandium City,no,00A,AAA,AMA,http://www.airport.kg/index.php?option=com_con...,https://en.wikipedia.org/wiki/List_of_airports...,"ZZZW, ZZZW, ZYW, YK96"
74462,313629,ZZZZ,small_airport,Satsuma I≈çjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,AAA,RJX7,http://www.airport.kg/index.php?option=com_con...,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

In [56]:
#now all null values including strings, categorial and numeric are handled

In [57]:
#if number of nullrows are less in number then we can go for df.dropna()
#this deletes the less significant null rows under the columns